tasks:
  install:
    image: "node:carbon"
    command:
      - yarn
    args:
      - install
  build:
    image: "node:carbon"
    command:
      - yarn
    args:
      - build
  test:
    image: "node:carbon"
    command:
      - yarn
    args:
      - test
  coverage:
    image: "node:carbon"
    command:
      - yarn
    args:
      - coverage
  codecov:
    image: "node:carbon"
    env:
      - CODECOV_TOKEN
    command:
      - yarn
    args:
      - codecov
      - --token=$(CODECOV_TOKEN)
