notifications:
  email: false

branches:
  only:
    - main
    - /^v\d+\.\d+\.\d+/

language: node_js

node_js:
  - "10"
  - "12"

install:
  - yarn install --frozen-lockfile --non-interactive

jobs:
  include:
    - stage: Build
      script:
        - yarn build
    - stage: Test
      script:
        - yarn build
        - yarn test
    - stage: Build Examples
      script:
        - yarn build
        - cd $TRAVIS_BUILD_DIR/examples
        - for dir in $TRAVIS_BUILD_DIR/examples/*; do (cd "$dir"; yarn; yarn clean; yarn build; cd ../); done
